# Generated by Django 5.2.6 on 2025-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('claimant_name', models.CharField(max_length=200)),
                ('code_13_digit', models.CharField(max_length=20)),
                ('claim_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(max_length=20)),
                ('village_name', models.CharField(default='Pimpalgaon Khu', max_length=100)),
                ('taluka', models.CharField(default='Sakri', max_length=100)),
                ('district', models.CharField(default='Dhule', max_length=100)),
            ],
            options={
                'unique_together': {('serial_number', 'village_name')},
            },
        ),
    ]
