# Generated by Django 5.2.6 on 2025-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_claimant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimant',
            name='code_13_digit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
